# Generated by Django 5.2.4 on 2026-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('referral', 'Referral'), ('partner_submitted', 'Partner Submitted')], default='direct', max_length=20),
        ),
    ]
