# Generated by Django 5.2.4 on 2026-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_alter_dealsubmission_status_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ppl_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
