# Generated by Django 5.2.4 on 2026-06-12 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('capital-strategy', 'Capital Strategy'), ('preparation', 'Preparation'), ('government-programs', 'Government Programs'), ('access-to-capital', 'Access to Capital'), ('market-analysis', 'Market Analysis'), ('strategy', 'Strategy'), ('cash-flow', 'Cash Flow'), ('industry-focus', 'Industry Focus'), ('sba-loans', 'SBA Loans'), ('business-growth', 'Business Growth')], default='capital-strategy', max_length=50)),
                ('excerpt', models.TextField(blank=True, max_length=600)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('read_time', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
