# Generated by Django 5.2.4 on 2026-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('capital-strategy', 'Capital Strategy'), ('preparation', 'Preparation'), ('government-programs', 'Government Programs'), ('access-to-capital', 'Access to Capital'), ('market-analysis', 'Market Analysis'), ('strategy', 'Strategy'), ('cash-flow', 'Cash Flow'), ('industry-focus', 'Industry Focus'), ('sba-loans', 'SBA Loans'), ('business-growth', 'Business Growth')], default='capital-strategy', max_length=100),
        ),
    ]
